// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:core/core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpGBzn2gmgA0tIL2LnokqBR8O7HA7aKs8',
    appId: '1:91509058041:android:4f112c3d6049ebaf1af528',
    messagingSenderId: '91509058041',
    projectId: 'a-s-a-a19b3',
    databaseURL: 'https://a-s-a-a19b3.firebaseio.com',
    storageBucket: 'a-s-a-a19b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYNZZpixYXtzxItHjXFR3zbPTOK6Fsdn8',
    appId: '1:91509058041:ios:c998d90e7c15d4bf1af528',
    messagingSenderId: '91509058041',
    projectId: 'a-s-a-a19b3',
    databaseURL: 'https://a-s-a-a19b3.firebaseio.com',
    storageBucket: 'a-s-a-a19b3.appspot.com',
    androidClientId:
        '91509058041-78okeh1p36ctosaer3e6m8413u6mmnr9.apps.googleusercontent.com',
    iosClientId:
        '91509058041-dav99d2a4m7doldp31ng0biaigp12mrv.apps.googleusercontent.com',
    iosBundleId: 'zeffry.reynando.bimtama.bimtama',
  );
}
